name: Check
on: push
jobs:
  setup:
    name: Setup OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp-version: ['24.x']
        elixir-version: [1.13.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Init setup
        run: echo "Init setup..."
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: Cache
        id: cache-elixir
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: |
            ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install Dependencies
        if: steps.cache-elixir.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile --only-deps
          mix dialyzer --plt
  mix-test:
    name: Test
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp-version: ['24.x']
        elixir-version: [1.13.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: Setup package dependencies
        run:
          sudo apt -y install inotify-tools
      - name: Retrieve cached Elixir setup
        uses: actions/cache@v3
        id: cache-elixir
        with:
          path: |
            deps
            _build
            priv/plts
          key: |
            ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Mix deps.get
        run: |
          mix deps.get
          mix deps.compile --only-deps
      - name: Mix Test
        run: mix test
  mix-dialyzer:
    name: Dialyzer
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp-version: ['24.x']
        elixir-version: [1.13.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: Retrieve cached Elixir setup
        uses: actions/cache@v3
        id: cache-elixir
        with:
          path: |
            deps
            _build
            priv/plts
          key: |
            ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}
      - name: Mix Dialyzer
        run: mix dialyzer
  mix-format:
    name: Format
    needs: setup
    env:
      MIX_ENV: test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        otp-version: ['24.x']
        elixir-version: [1.13.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: Retrieve cached Elixir setup
        uses: actions/cache@v3
        id: cache-elixir
        with:
          path: |
            deps
            _build
            priv/plts
          key: |
            ${{ runner.os }}-${{ matrix.otp-version }}-${{ matrix.elixir-version }}-${{ hashFiles('mix.lock') }}
      - name: Mix Format Check
        run: mix format --check-formatted
